server.port: 8090


spring.cloud.stream.bindings.output.contentTye: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.clientmv:
  destination: clientmv
  producer:
    headerMode: raw
spring.cloud.stream.bindings.clout:
  destination: clout
  producer:
    headerMode: raw
spring.cloud.stream.bindings.clin:
  destination: clout
  group: clout
  consumer:
    headerMode: raw
spring.cloud.stream.bindings.clcout:
  destination: clcout
  producer:
    headerMode: raw
spring.cloud.stream.bindings.clcin:
  destination: clcout
  group: clcout
  consumer:
    headerMode: raw
