server.port: 8070

spring.cloud.stream.bindings.output.contentTye: application/json
spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000
spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
spring.cloud.stream.bindings.medewerkermv:
  destination: medewerkermv
  producer:
    headerMode: raw
spring.cloud.stream.bindings.medewerkercountmv:
  destination: medewerkercountmv
  producer:
    headerMode: raw
spring.cloud.stream.bindings.mdout:
  destination: mdout
  producer:
    headerMode: raw
spring.cloud.stream.bindings.mdin:
  destination: mdout
  group: mdout
  consumer:
    headerMode: raw
spring.cloud.stream.bindings.mdcout:
  destination: mdcout
  producer:
    headerMode: raw
spring.cloud.stream.bindings.mdcin:
  destination: mdcout
  group: mdcout
  consumer:
    headerMode: raw
